### ISSUE TITLE
how to clear?

### ISSUE THREAD

**Issue by Kikobeats** [joehand/neat-log#12]
at version 1.x you can do it with `bus.clear` but now it's not available at 2.x.

**Comment by joehand** [comment]
hmm ya. There is no clear function in diffy. We can see how that was being done before in ansi-diff or we could also just write an empty string to render.

**Comment by joehand** [comment]
Looks like writing an empty string is the way to go! https://github.com/mafintosh/ansi-diff-stream/blob/master/index.js#L44

**Comment by joehand** [comment]
Take a look at https://github.com/joehand/neat-log/pull/14 and let me know if you have thoughts. Not quite sure the best way to approach it.
