### ISSUE TITLE
deal with lines that get split

### ISSUE THREAD

**Issue by joehand** [joehand/neat-log#4]
If the terminal is small long lines get split and differ goes crazy. 

Mafintosh had a few ideas:

* Just clear regularly
* check if lines are too long and split them (this could happen in status-logger)
* one other thing I forgot.

**Comment by lachenmayer** [comment]
Ava's default 'mini reporter' seems to handle wrapped lines just fine.

Their implementation is here: https://github.com/avajs/ava/blob/master/lib/reporters/mini.js#L278

`process.stdout.columns` returns the width of the terminal.

There is also a resize event: https://nodejs.org/api/tty.html#tty_event_resize

**Comment by joehand** [comment]
(copied from IRC for posterity)

ya that'd work, I use the columns thing in the dat cli [using cli truncate](https://github.com/datproject/dat/blob/master/src/ui/components/import-progress.js#L64). Think we could check each line before render and split it if it's too long.

The resize should just be because of the line bug. It's [handled in status-logger](https://github.com/joehand/status-logger/blob/master/index.js#L17) and I think it works if the lines are short.

**Comment by joehand** [comment]
Should be fixed with `1.1.2`! 

https://github.com/joehand/status-logger/commit/ab3567c0a38a69e9b4bbd3a9101606a244239ba9

Opened #8 for the resize issue. Seems like its still buggy with the line fix 😕 .
