### ISSUE TITLE
Behaves weirdly for long output

### ISSUE THREAD

**Issue by Frando** [joehand/neat-log#6]
I'm using neat-log for [dat-share-all](https://github.com/Frando/dat-share-all). When the output gets longer than one page, neat-log behaves weirdly (see Frando/dat-share-all#1). I assumed that scrolling would be an issue whenever a rerender occurs, but also the rerender does not seem to work correctly when the output is longer than one page, lines appear all over the place.

Not sure what the expected behavior is.

**Comment by joehand** [comment]
Yea, it breaks when a line gets longer than one terminal line. Is that what you're experiencing? Screenshot would be helpful.

I think the easiest way to fix this immediately is to call `.reset()` on the ansi-diff-stream whenever you make a breaking UI update. I can expose this as `.reset()` or something to make it easier.

See some other possible solutions in https://github.com/joehand/neat-log/issues/4

**Comment by joehand** [comment]
Check if using https://github.com/joehand/neat-log/pull/7 can help fix it. You could also try `bus.clear()` before adding a new dat or something. That will clear all existing output before printing again.

**Comment by joehand** [comment]
Closing this in favor of #4 because I keep getting confused =). Gonna try to add a fix along with #7.

**Comment by joehand** [comment]
Should be fixed with `1.1.2`! Thanks for bringing this to my attention again! ❤️  Was something that bothered me for way too long.

https://github.com/joehand/status-logger/commit/ab3567c0a38a69e9b4bbd3a9101606a244239ba9

**Comment by Frando** [comment]
Yep, much better already. Thanks. I will reopen this if I still find places where the output breaks for long output.
