### ISSUE TITLE
How to indent output

### ISSUE THREAD

**Issue by Kikobeats** [joehand/neat-log#9]
I'm trying to output and indent string:

```js
function headerView (state) {
  return `\tHello World!`
}
```

but doesn't work, looks like diff comparison remove them?

**Comment by joehand** [comment]
Ah yes! That is probably a bug/overly greedy trimming. I think I hit this in the Dat CLI but can't find right now how I solved it. It is trimmed here: https://github.com/joehand/neat-log/blob/master/output.js#L12

I'm 90% sure its possible, but cannot remember how!

**Comment by Kikobeats** [comment]
Why not exclude `\t`, `\b`, `\n` etc alias?

**Comment by joehand** [comment]
Yes, that'd be great!

**Comment by joehand** [comment]
I think we may be able to close this now too?

**Comment by Kikobeats** [comment]
yes!
